name: Lint and E2E tests

on:
  workflow_dispatch:
  pull_request:
    branches:
    - master

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        uses: cypress-io/github-action@v6
        with:
          runTests: false

      - name: Lint
        run: pnpm run lint

      - name: E2E tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          config: baseUrl=https://localhost:3000/
          start: pnpm run dev
          wait-on: 'https://localhost:3000'
