name: Lint code

on:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'
          registry-url: 'https://registry.npmjs.org'

      - name: Install and lint
        run: pnpm install --frozen-lockfile && pnpm run lint
